export * from './account.service';
import { AccountService } from './account.service';
export * from './appStageDocuments.service';
import { AppStageDocumentsService } from './appStageDocuments.service';
export * from './application.service';
import { ApplicationService } from './application.service';
export * from './applicationProcesses.service';
import { ApplicationProcessesService } from './applicationProcesses.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './generalReport.service';
import { GeneralReportService } from './generalReport.service';
export * from './inspection.service';
import { InspectionService } from './inspection.service';
export * from './library.service';
import { LibraryService } from './library.service';
export * from './licenses.service';
import { LicensesService } from './licenses.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './schedules.service';
import { SchedulesService } from './schedules.service';
export * from './staff.service';
import { StaffService } from './staff.service';
export const APIS = [AccountService, AppStageDocumentsService, ApplicationService, ApplicationProcessesService, AuthService, CompanyService, GeneralReportService, InspectionService, LibraryService, LicensesService, LocationService, MessageService, PaymentService, SchedulesService, StaffService];
