/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationReportViewModel { 
    startDate?: string | null;
    toDate?: string | null;
    status?: string | null;
    applicationTypeId?: number | null;
    readonly min?: string;
    readonly max?: string;
}

