/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplictionViewModel { 
    vesselTypeId?: number;
    imoNumber?: string | null;
    vesselName?: string | null;
    loadingPort?: string | null;
    dischargePort?: string | null;
    marketerName?: string | null;
    productId?: number;
}

