/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyModel { 
    user_Id?: string | null;
    name?: string | null;
    business_Type?: string | null;
    registered_Address_Id?: string | null;
    operational_Address_Id?: string | null;
    affiliate?: string | null;
    nationality?: string | null;
    contact_FirstName?: string | null;
    contact_LastName?: string | null;
    contact_Phone?: string | null;
    year_Incorporated?: string | null;
    rC_Number?: string | null;
    tin_Number?: string | null;
    no_Staff?: string | null;
    no_Expatriate?: string | null;
    total_Asset?: string | null;
    yearly_Revenue?: string | null;
    accident?: string | null;
    accident_Report?: string | null;
    training_Program?: string | null;
    mission_Vision?: string | null;
    hse?: string | null;
    hseDoc?: string | null;
    date?: string | null;
    isCompleted?: string | null;
    elps_Id?: string | null;
    id?: number;
}

