/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyModel } from './companyModel';
import { DirectorModel } from './directorModel';
import { RegisteredAddress } from './registeredAddress';
import { DocumentModel } from './documentModel';


export interface CompanyInformation { 
    company?: CompanyModel;
    registeredAddress?: RegisteredAddress;
    operationalAddress?: RegisteredAddress;
    documentModel?: Array<DocumentModel> | null;
    director?: DirectorModel;
}

