/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisteredAddress } from './registeredAddress';


export interface DirectorModel { 
    id?: number;
    company_Id?: number;
    firstName?: string | null;
    lastName?: string | null;
    address_Id?: number;
    telephone?: string | null;
    nationality?: number;
    address?: RegisteredAddress;
}

