/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentModel { 
    documentName?: string | null;
    docId?: number;
    dateAdded?: string;
    dateModified?: string;
    source?: string | null;
    uniqueId?: string | null;
    fileId?: number;
    documentTypeName?: string | null;
    baseorTran?: string | null;
    isMandatory?: string | null;
    uploadDocumentUrl?: string | null;
}

