/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionDTO } from './inspectionDTO';


export interface InspectionResponse { 
    success?: boolean;
    message?: string | null;
    totalRecords?: number;
    responsecode?: string | null;
    data?: Array<InspectionDTO> | null;
}

