/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisteredAddress { 
    address_1?: string | null;
    address_2?: string | null;
    city?: string | null;
    country_Id?: number;
    stateId?: number;
    countryName?: string | null;
    stateName?: string | null;
    postal_code?: string | null;
    type?: string | null;
    id?: number;
}

