/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleViewModel { 
    id?: number | null;
    applicationId?: number;
    scheduleType?: string | null;
    scheduledDate?: string;
    nominatedStaffId?: string | null;
    scheduleMessage?: string | null;
    approvalMessage?: string | null;
    isAccepted?: boolean;
    clientMessage?: string | null;
    contactName?: string | null;
    phoneNo?: string | null;
    expiryDate?: string | null;
    act?: string | null;
}

