/**
 * CVC API
 * Authorized Tasks API using JWT Authentication and refresh Tokens
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkFlow { 
    id?: number;
    vesselTypeId?: number;
    fromLocationId?: number | null;
    toLocationId?: number | null;
    officeId?: number | null;
    applicationTypeId?: number | null;
    triggeredByRole?: string | null;
    action?: string | null;
    targetRole?: string | null;
    rate?: string | null;
    status?: string | null;
    isArchived?: boolean;
}

